Allow customization config files for apache2
pkgr/addon-apache2 pull request #6
Opened 2022-06-01 09:21 UTC by oliverguenther

OpenProject provides some features that require customization of the apache2 config files. In order to do that, we have until now recommended to add a custom include under /etc/openproject/addons/apache2/includes/vhost.

But that folder is cleaned on every installation. To remedy that, I'm suggesting we add a customization dir that the user can put extensions into without getting removed.

I first contemplated using a special naming in the conf folders, but that would make migration a bit more tedious.

2022-06-01 19:16 UTC, crohr requested changes
I would use custom instead of customization (less confusing regarding z or s)

2022-06-01 19:16 UTC, crohr commented on bin/postinstall
> +SERVERCUSTOMIZATION_DIR="/etc/${APP_NAME}/addons/apache2/includes/server"
```suggestion
SERVER_CUSTOMIZATION_DIR="/etc/${APP_NAME}/addons/apache2/custom/server"
```

2022-06-01 19:16 UTC, crohr commented on bin/postinstall
> +VHOST_CUSTOMIZATION_DIR="/etc/${APP_NAME}/addons/apache2/includes/vhost"
```suggestion
VHOST_CUSTOMIZATION_DIR="/etc/${APP_NAME}/addons/apache2/custom/vhost"
```

2022-06-01 19:16 UTC, crohr commented on conf/web-raw
> +Include /etc/_APP_NAME_/addons/apache2/customization/server/*.conf
```suggestion
Include /etc/_APP_NAME_/addons/apache2/custom/server/*.conf
```

2022-06-01 19:16 UTC, crohr commented on conf/web-raw
> +  Include /etc/_APP_NAME_/addons/apache2/customization/vhost/*.conf
```suggestion
  Include /etc/_APP_NAME_/addons/apache2/custom/vhost/*.conf
```

2022-06-02 06:01 UTC, oliverguenther commented
I wish I reviewed the code before making the suggestion. Thanks for the correction!

2022-06-02 06:02 UTC, merged